packages:
  - .
autoInstallPeers: false
overrides:
  next: '$next'
patchedDependencies:
  next@16.2.11: patches/next@16.2.11.patch
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  sharp: true
  unrs-resolver: true
