name: CI & CD
on:
  push:
    branches:
      - main
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm
      - name: Install
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          forceOrphan: true
