name: CI & CD
on:
  push:
    branches:
      - main
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install & build
        run: |
          npm install
          npm run export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          forceOrphan: true
